### PR TITLE
Added more legible time format and some settings

### PR DESCRIPTION
**Pull request by caioflores**
Added 1h30m time format in all graphs (but it's missing it in max/average marks).
Added vscode lauch script.
Added some rules in gitignore.

### CODE REVIEW

**Comment by hangxingliu** [comment]
Firstly. Thanks for your pull request.
I will merge it in recent days.

There have two points in your pull request I am considering.

1. replacing the y axis unit of 24 hours report chart from minute to hour
  - Because the maximum value is less than 60 minutes in 24 hours report.
2. ignore front-end dist files
  - Firstly, It means when somebody install this server side program (or install this VS Code extension ).
Even if they don't modify front-end files and just want to quickly use it, they should install more devDependencies (I declare these modules in `install-builder-dependencies` file)  to build front-end files again.
  - Secondary, The number of dist files is small, just 5 files included two sources map files. And They are not binary. 

If you have your reason in pull request. You can comment in here for discussing.

**Comment by caioflores** [comment]
1- @hangxingliu I replaced the y axis because my function returns just the minutes if the time is less than 1 hour. So the same function can be used for hours/minutes legends.

2 - I got it. My only considerations here were possible conflicts when pushing this files and the repo size. But ok, no problem, I'll remove it from the ignore soon.

**Comment by hangxingliu** [comment]
OK, I will merge this pull request one hour later.

**Comment by hangxingliu** [comment]
Merged (cheery-pick) to  branch `0.5.0-develop`

**Comment by hangxingliu** [comment]
Oh my god, you forget test. and me too ...

There has two bug in develop bran now:

1. 1.3h => 1h 78m
2. international bug(for example: In Chinese language, this report looks like: "you totally work 1h 30m hours" )

**Comment by caioflores** [comment]
Sry, my bad. And thanks for the refactor, your code approach was really better.

**Pull request closed without merging**
